apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: kube-system
---
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    task: logging
    k8s-app: logging-elasticsearch
  namespace: kube-system
data:
    elasticsearch.yml: |
      cluster.name: local-cluster
      network.host: 0.0.0.0
      http.port: 9200
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logging-elasticsearch
  namespace: kube-system
  labels:
    task: logging
    k8s-app: logging-elasticsearch
spec:
  template:
    metadata:
      labels:
        k8s-app: logging-elasticsearch
      name: logging-elasticsearch
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: logging-elasticsearch
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: schikin/elasticsearch:5.5
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 2048Mi #1g - heap, 1g - offheap Lucene memory
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: elasticsearch-storage
          mountPath: /data
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /config
      volumes:
      - name: elasticsearch-storage
        persistentVolumeClaim:
          claimName: elasticsearch-storage
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
      securityContext:
       fsGroup: 101
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: logging
    kubernetes.io/name: logging-elasticsearch
  name: logging-elasticsearch
  namespace: kube-system
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9300
    targetPort: 9300
    name: internode
  selector:
    k8s-app: logging-elasticsearch
